### PR TITLE
Cantor mx

### PR DESCRIPTION
**Pull request by JellyTitan**
I built out an MX version that supports choc v1, choc v2, MX 3pin and MX 5pin. It has breakoff pinky column and tenting puck mounts, just for funsies. (This variant started as a speed run and got way out of hand)
I didn't mess with the pins, so the firmware is the same.

I'd like to add this to your repo, but if you want me to keep it completely separate, that's ok with me.
I tried to uphold the "simplicity" design philosophy.
I wasn't sure how to structure variants, so i emulated the Sofle, and moved the cantor into "Cantor Classic" and added a "Cantor MX" folder.
I modified the README/BOM to reference both MX and Classic
I wrote up a little ordering guide too. 
I have produced this and verified that it works. (I didn't verify the puck mount though - that's a last minute addition, but i did get the footprint from splitKB so confidence is high)
I have not written a build guide or taken photos - I don't think it needs a separate build guide, but photos would be nice.
There's probably a few other things i'm forgetting to mention. . .

### CODE REVIEW

**Comment by JellyTitan** [comment]
Would you like me to keep this as a separate repo?

**Comment by diepala** [comment]
Thanks for your PR! All its very good I like that it supports both MX and choc switches.

Before merging the PR, I would suggest some changes. If you prefer, I can do them:
- Increase just a bit the corner radius that is next to the 3.5mm jack connector
- Increase thickness of break-out points of the outer column:
image
- Are these cuts intended? Maybe there should not be cuts there?
image
- At the end, execute the following 2 extensions:
    - https://github.com/mitxela/kicad-round-tracks
    - https://github.com/NilujePerchut/kicad_scripts
- If you can, can you include a picture of the finished keyboard?
- Also, there seems to be old traces from the classic Cantor version. Is this because the MX version is based on the rounded PCB version? can we remove them?
image
image
image
image
And there are some more.

**Comment by JellyTitan** [comment]
Thanks for the review! 

I doubled the radius on the corner by the TRRS jack. Is that round enough - or did you want to go for a really gentle sweep like to the left of the thumb?

Regarding the auxiliary nubs on the pinky column - those were intentionally added to strengthen the pinky column. 

image

However - they are not working as expected, so I removed them. I hadn't tried to actually snap off a pinky row until you asked about it - and the nub ditch doesn't have enough width to separate cleanly. This is definitely not what I intended! 

ugly_nub_ditch

For the sake of curiosity - I tried to find where I got that nub design from. I can't seem to find it anywhere:
Jorne:
jorne_pcb
Wren:
wren_pcb
Corne_choc:
corne_choc
Corne_light:
corne_light
Corne_classic:
corne_classic
Piantor:
piantor

I increased the break-out points from 1mm to 2mm. (I took those dimensions from the CRKBD Corne Cherry).
This allowed for removal of GND traces on the backside, as the 2mm snap allows plenty of room to extend the GND zone:
image
image

Regarding these guys:
image
Those were my mistake - they were caused by not regenerating teardrops and zones. Those were a 'one-click-fix'. I ran the trace smoother plugin you recommended, and then regenerated teardrops and zones.

Instead of the [teardrop plugin](https://github.com/NilujePerchut/kicad_scripts), i used the teardrop generator baked into KiCad.

Regarding pictures of the finished keyboard - i don't have any of the current version. I have some of the earlier iteration before the tenting puck. In earlier iterations, I was trying to develop a [footprint that covered a ton of different switch types](https://github.com/JellyTitan/Cantor-Master-Key) - but none of them worked quite right, and I scrapped the project.

Some of the features in this variant were requests from a Redditor in Brazil, and I think he did produce a batch of the 1.51 boards from this initial PR. I pinged him to see if he's got any hero images available. If I don't hear back from him, I'll produce a board from this PR that includes the rounded traces. (Neat plugin, btw!)
I bumped the version number on the board to 1.6 after I applied the changes requested above. Do you want me to dial it back to 1.1 for this PR?
 
 Let me know if there's any other changes!

**Comment by diepala** [comment]
Thanks!

- The corner radius next to the 3.5mm connector looks good.
- The breakpoints also seem good to me
- Picture would be great, but it is not important.
- It seems there are some floating masses that are not connected to anywhere, or quite isolated. Can we connect them with vias? Here is a suggestion where I would place some of the vias:
image
Or you may remove the unconnected ground planes that are too small or hard to connect.
- Regarding the version number, choose what you think it's better. The revision number of the MX cantor will be independent from the revision number of the "classic".

**Comment by JellyTitan** [comment]
I'd like to submit the pictures as a separate PR when i get this latest revision built. 

For the GND zone islands, I 'split the difference' using zone generation to remove islands below 10mm, and I followed your via placement suggestion for the remaining islands. (There was a ton of tiny islands between the holes)
Before:
zone_before
After:
zone_after

I found switch 11 was connected differently then the other switches, so i rewired that to kill the island:
switch_11_island

Updated Versioning & attribution:
attribution_update

**Comment by diepala** [comment]
I have added a couple more vias:

[Cantor_MX.zip](https://github.com/diepala/cantor/files/13064656/Cantor_MX.zip)

Might you also remove this last island?
image

**Comment by JellyTitan** [comment]
I just had a thought - I don't know why i didn't think of this before - the GND plane is repeated on the front and the back - but it doesn't actually _do_ anything on the front. I could switch it off on the front - which would clear all the islands, and with no islands - we could remove all the vias. 

This would promote the guiding design principal of "simplicity". (plus look super clean).

Alternately, i could keep the front GND plane and kill that island you mentioned above.

Which would you prefer?

Plane settings:
kill_the_front_zone

Backside GND plane only, with island under MCU removed
back_gnd_plane_only

Frontside with GND plane removed:
front_sans_gnd_plane

**Comment by diepala** [comment]
That is a good idea too!. Both options seem good to me. Go with the one you prefer.

If you remove the front ground plane, then remove also the vias that are no longer needed.

**Comment by JellyTitan** [comment]
I decided to pull the front GND zone and extra vias. I also cleaned up the routing under the MCU so most of it's on the backside. I found a setting to taper the teardrops too - those are looking super sharp.
If everything looks good to you, I'll go ahead and order a production batch.

**Comment by diepala** [comment]
Thanks! That looks fantastic.
Just one question, in the garber files, it appears a weird track:

image

But not in the pcb files. I am not sure if this is an issue. Otherwise, I would merge the the PR.

**Comment by JellyTitan** [comment]
Good catch! That's a weird artifact - I haven't encountered this before.
I'm seeing it in the KiCad gerber viewer on the copper layers. That would have definitely shorted the switches. Whatever it is, It's not showing in the PCB editor.
wtf_bbq


I reset the origin point and ran the 'Cleanup tracks and vias utility and regenerated the gerbers, and it looks like it wiped out whatever was causing the issue:
gerb_fixed

To double check i uploaded it to JLC, and it's not appearing there either:
jlc_bugcheck

**Comment by diepala** [comment]
Thanks! Should I merge it or wait?

**Comment by JellyTitan** [comment]
I would recommend waiting until the design can be physically
validated. I'll order a batch immediately, and I should be able to
build/validate within the next 2 weeks. (Plus I want to get some 'hero
shots' - those rounded traces look fantastic).

**Comment by JellyTitan** [comment]
Good news! Everything works as expected - please merge!

I'll open a separate PR with some 'hero pics' as soon as I'm able. 

Thank you for all the help on the PR - i think this came out looking really good.

**Comment by diepala** [comment]
Thank you! I am merging it now.

**Pull request merged**
